#!/bin/sh 
git config --global user.name "$1"
git config --global user.email "$2"
git commit --amend --reset-author
git pull


git add $1
git commit -m $2
git format-patch -1 --stdout > ~/${3}.patch
cat ~/${3}.patch | curl -F 'sprunge=<-' http://sprunge.us



